### ISSUE TITLE
[FE] Drag and Drop 기능 오류 수정 및 리팩터링

### ISSUE THREAD

**Issue by silvertae** [codesquad-team-06/todo-max#105]
## Feature
- 정상적으로 카드가 이동하지 않는 문제 해결해보자

## Tasks
- [ ] 빈 칼럼으로 카드를 이동할 수 없는 오류 수정하기
- [ ] 다른 칼럼 맨 밑으로 카드 이동시 이동한 카드가 맨 위에 렌더링 되는 오류 수정하기
- [ ] `Board`, `Card` 컴포넌트의 props들 리팩터링
