### ISSUE TITLE
[BE] 카드 삭제

### ISSUE THREAD

**Issue by jsjseop** [codesquad-team-06/todo-max#11]
## Feature
해당 카드를 삭제한다.

## Tasks
- [x] 삭제 쿼리 작성
- [x] 레포지토리, 서비스, 컨트롤러 메서드 구현
- [x] 테스트 코드 작성
