### ISSUE TITLE
[BE] RDS 환경 구축

### ISSUE THREAD

**Issue by Ojeegu** [codesquad-team-06/todo-max#12]
## Feature
AWS RDS 서비스를 이용하여 MySQL을 사용할 수 있도록 환경 구축

## Tasks
- [ ] RDS MySQL 생성
- [ ] ERD를 참고하여 테이블 생성
- [ ] 디폴트 칼럼 값(3개) 및 디폴트 액션 값(4개) 삽입
