### ISSUE TITLE
[BE] 카드 이동

### ISSUE THREAD

**Issue by swinb** [codesquad-team-06/todo-max#13]
## Feature
사용자의 요청에 따라 카드의 위치를 이동시킨다.
## Tasks
- [ ] 1 Request DTO 구현
- [ ] 2 position 정렬 메소드 구현
- [ ] 3 DB UPDATE 로직 구현
- [ ] 4 테스트코드 작성
