### ISSUE TITLE
[FE] 카드 등록 기능 구현

### ISSUE THREAD

**Issue by silvertae** [codesquad-team-06/todo-max#27]
## Feature
- 사용자는 칼럼에 새로운 카드를 등록할 수 있다.

## Tasks
- [x] 칼럼 타이틀 옆 + 버튼을 클릭하면 해당 컬럼에 새로운 카드를 등록할 수 있는 박스가 나타난다.
- [x] + 버튼을 다시 한 번 더 누르거나 카드의 [취소 버튼]을 누르면 박스가 사라진다.
- [x] 카드에 내용을 입력하면 [등록 버튼]이 활성화된다.
    - [x] 카드의 내용이 공백이면 [등록 버튼]은 비 활성화된다.
    - [x] 카드의 글자 수 제한은 500자 이내이다.
    - [x] 글의 길이에 맞춰 박스의 높이가 변한다.
- [x] 활성화 된 등록 버튼을 누르면 서버로 Post 요청을 보낸다.
