### ISSUE TITLE
[FE] 카드 수정 기능 구현

### ISSUE THREAD

**Issue by Kakamotobi** [codesquad-team-06/todo-max#28]
## Feature
- 사용자는 칼럼에 새로운 카드를 수정할 수 있다.

## Tasks
- [x] 카드의 [수정 버튼]을 누르면 등록 박스와 동일한 스타일로 전환되면서 수정이 가능해진다.
- [x] 카드 수정 상태에서 [취소 버튼]을 누르면 변경 사항이 반영되지 않고 수정 상태가 풀린다.
- [x] 내용을 모두 삭제하면 [저장 버튼]이 비활성화된다.
- [x] 내용을 수정한 후 [저장 버튼]을 누르면 변경사항이 반영된 카드로 바뀐다.
