### ISSUE TITLE
[BE] 예외 처리 매커니즘 구현

### ISSUE THREAD

**Issue by Ojeegu** [codesquad-team-06/todo-max#29]
## Feature
 API 응답 실패 시 예외 처리 매커니즘 구현

## Tasks
- [ ] 예외를 나타내는 ErrorCode 열거형과 예외 클래스 구현
- [ ] 예외 발생 시 클라이언트에게 반환할 ErrorResponse 작성
- [ ] GlobalExceptionHandler 클래스 구현
