### ISSUE TITLE
[FE] 활동기록 레이어와 모달창 UI 작업

### ISSUE THREAD

**Issue by silvertae** [codesquad-team-06/todo-max#3]
## Feature
- 활동기록 레이어의 UI를 구현
- 취소 모달창의 UI를 구현

## Tasks
- [x] 활동 기록 레이어 컴포넌트
    - [x] 활동 기록 카드 컴포넌트
- [x] 삭제 모달창
    - [x] 전체 활동 기록 삭제 모달
    - [x] 카드 삭제 모달

**Comment by silvertae** [comment]
Modal UI 구현 중 z-index 관련 trouble shooting
- css에 1이 아닌 opacity 속성이 있으면 요소가 새로운 stacking order에 배치되기 때문에 발생한 문제
- 우선 background-color를 rgba를 사용해서 투명도를 0.3으로 지정해둠

참고) [https://developer.mozilla.org/en-US/docs/Web/CSS/opacity#description](url)
