### ISSUE TITLE
[BE] 프로젝트 초기화

### ISSUE THREAD

**Issue by yonghwankim-dev** [codesquad-team-06/todo-max#4]
## Feature
- TODO 서비스를 구현하기 위해서 스프링 부트 프로젝트를 초기화합니다.

## Tasks
- [x] Card 엔티티 클래스 구현
- [x] Column 엔티티 클래스 구현
- [x] History 엔티티 클래스 구현
- [x] 각 엔티티 클래스에 해당하는 Controller, Service, Repository 스켈레톤 코드 구현
