### ISSUE TITLE
[FE] 새로운 카드 등록 기능 구현 완성 및 헤더영역 작업

### ISSUE THREAD

**Issue by silvertae** [codesquad-team-06/todo-max#40]
## Feature
- [x] 사용자 활동기록 레이어 토글 기능 및 디폴트 문구 출력 기능
- [x] 새로운 카드 등록시 화면에 새로운 카드가 렌더링 되는 기능

## Tasks
- [x] Header에 활동기록 레이어의 열고 닫힘을 관리하는 state 추가
- [x] 사용자 활동 기록이 없을 때 렌더링 되는 ActivityHistory UI 구현
- [x] 새로운 카드 등록 시 Board 컴포넌트의 state를 변경시키는 핸들러 구현
- [x] 새로운 카드 등록시 해당 Column 가장 위에 카드가 추가되도록 구현

option) Column의 타이틀 옆 카운트되는 숫자 min, max 정해두기
