### ISSUE TITLE
[BE] Epic2-Story2. 히스토리 조회 API 구현

### ISSUE THREAD

**Issue by Ojeegu** [codesquad-team-06/todo-max#5]
## Feature
사용자가 활동 기록 버튼을 클릭했을 때 활동 기록 목록이 보이도록 API 구현

## Tasks
- [ ] DB에 저장된 히스토리 목록 불러오기
- [ ] 불러온 히스토리 목록 반환하기
- [ ] 테스트 코드 작성
