### ISSUE TITLE
[FE] 활동기록 레이어 애니메이션 기능

### ISSUE THREAD

**Issue by silvertae** [codesquad-team-06/todo-max#51]
## Feature
- 활동 기록 레이어가 나타나고 사라질 때 애니메이션 기능을 추가한다.

## Tasks
- [x] 히스토리 버튼 클릭시 fetch한 데이터를 이용해 메인 영역 바깥에 ActivityHistory를 렌더링한다.
- [x] 렌더링이 끝난 ActivityHistory 컴포넌트는 헤더의 히스토리 버튼 아래쪽 영역으로 슬라이드하면서 이동한다.
- [x] 슬라이드 되는 동시에 fade in 효과를 적용한다.
- [x] 히스토리 버튼이나 닫기 버튼 클릭시 나타나날 때 애니메이션이 반대로 적용되며 화면밖으로 사라진다.

추가 작업) ActivityHistoryItem이 5개 초과일 때 레이어가 더 이상 길어지지 않고 스크롤 생성되도록 변경

**Comment by silvertae** [comment]
- 레이어가 나타나는 애니메이션은 적용되는데 사라지는 애니메이션은 제대로 적용되지 않는 문제 (해결)
원인: Unmount 시 애니메이션 적용되지 않는 문제
