### ISSUE TITLE
[FE] 카드 Drag & Drop 구현

### ISSUE THREAD

**Issue by Kakamotobi** [codesquad-team-06/todo-max#53]
## Feature
- 카드 drag and drop

## Tasks
- [x] MouseMove
    - [x] `mouseMoveHandler` on `Board` component.
    - [x] Update `currMouseCoords` based on the mouse position. (clientX, clientY).
    - [x] Update selected `ColumnCard` position based on `currMouseCoords`.
    - [x] Render `CardShadow` upon dragging.
    - [x] Use `document.elementFromPoint(currentCoords)` to determine the element at the corresponding coordinates.
        - [x] `belowCard = elementAtPoint.closest(”li”)`.
        - [x] Calculate the mid y point of `belowCard` by using `getBoundingClientRect()`.
            - [x] To determine whether coming from above or below.
        - [x] Render `CardShadow` above/below based on the calculated mid y point.
- [x] MouseDown
    - [x] Update `dragCard`.
    - [x] Initialize `cardShadowPosition`.
    - [x] Initialize `currMouseCoords`.
- [x] MouseUp
    - [x] Determine `prevColumnId`, `nextColumnId`, `beforeCardId`, `afterCardId`.
    - [x] Send PUT request to server.
    - [x] Update `board` based on response.
- [x] 필요한 상태
    - [x] `currMouseCoords`
      - Keep track of the mouse's current coords.
      - Used to synchronize the card being dragged with the mouse's current coords.
        - Feed dragged card's `top`, `left` with the these coords.
      - Used to determine the card that is underneath the currently being dragged card using `elementAtPoint`.
    - [x] `dragCard`
      - Contains the reference for the card that is being dragged, and the card details.
      - `dragCard.cardRef` is used to temporarily remove pointer events on the card being dragged (in order to determine `belowCard`).
      - `dragCard.cardDetails` is used for feeding `CardShadow`.
    - [x] `currBelowCardId`
      - Used to determine whether this `Card` is the card that is currently below the dragged card, which is used to conditionally render `CardShadow`.
    - [x] `currCardShadowInsertPosition`
      - Used to determine whether `CardShadow` should be rendered above or below `belowCard`.
- [x] 필요한 컴포넌트
    - [x] 선택된 카드 위치를 대체할 CardShadow 컴포넌트 추가

**Comment by silvertae** [comment]
## [해결] 카드 이동이 많아질 때 나타나는 콘솔 에러 + 타입 에러
![스크린샷 2023-07-18 오후 3 49 30](https://github.com/codesquad-team-06/todo-max/assets/76121068/3429ad5e-f359-41f1-a125-668c3a2db258)

styled-components `attrs()` api를 사용해서 해결

참고) 
https://styled-components.com/docs/api#attrs
https://stackoverflow.com/questions/54639872/casting-styled-components-in-react-typescript

**Comment by silvertae** [comment]
## 카드 드래그 이동시 마우스 포인터 커서가 제대로 적용이 안되는 문제

### 밑에 다른 카드가 있을 때는 cursor: grab
![스크린샷 2023-07-20 오전 11 50 30](https://github.com/codesquad-team-06/todo-max/assets/76121068/a193a684-40d2-44c7-9a5c-e13b8cd91b0f)

### 밑에 잔상이 있을 때는 cursor: grabbing
![스크린샷 2023-07-20 오전 11 50 35](https://github.com/codesquad-team-06/todo-max/assets/76121068/c611cda2-18a6-401f-aafd-f3267a1b600f)

**Comment by silvertae** [comment]
## 카드 drop 시 기존 커서로 잡고 있던 카드가 안 놓아지는 문제

- `Card`의 mouseUpHandler에서 dragCard를 초기화하면서 Card의 position이 absolute에서 static 으로 변경되면서 카드가 떨어져야 하는데 안 떨어진다.
- 우선 CardShadow 에 mouseUpHandler를 props로 넘겨줘서 onMouseUp 이벤트에 걸어 해결
