### ISSUE TITLE
[BE] ER 다이어그램 및 SQL 쿼리 변경

### ISSUE THREAD

**Issue by Ojeegu** [codesquad-team-06/todo-max#60]
## Feature
Action table을 삭제하고 그와 관련된 변경 사항을 적용

## Tasks
- [x] ER 다이어그램의 Action table 삭제
- [x] History table의 action_id 컬럼 삭제
- [x] History table에 action_name 컬럼 추가
- [x] 테이블 생성 쿼리 변경
- [x] 샘플 데이터 쿼리 변경
