### ISSUE TITLE
[BE] Epic2-Story3. 히스토리 전체 삭제 API 구현

### ISSUE THREAD

**Issue by Ojeegu** [codesquad-team-06/todo-max#7]
## Feature
사용자가 전체 활동 기록 삭제 버튼을 클릭했을 때 목록에 있는 기록들을 삭제하는 기능 구현

## Tasks
- [ ] 삭제할 히스토리의 `is_deleted` 컬럼 값을 `true`로 변경
- [ ] 처리 결과를 반환
- [ ] 테스트 코드 작성
