### ISSUE TITLE
[BE] 히스토리 패키지 정리 및 예외 처리 구현

### ISSUE THREAD

**Issue by Ojeegu** [codesquad-team-06/todo-max#70]
## Feature
히스토리 패키지 코드 정리와 예외 처리 구현하기

## Tasks
- [ ] 히스토리 패키지 내 코드 정리
- [ ] id 데이터 타입 Long으로 맞추기
- [ ] Repository에서 예외 발생 구현
