### ISSUE TITLE
[BE] EC2에서 수동 배포를 위한 수동 배포 스크립트 작성 및 실행

### ISSUE THREAD

**Issue by yonghwankim-dev** [codesquad-team-06/todo-max#8]
## Feature
- EC2 인스턴스 환경에서 수동 배포를 위한 스크립트를 작성하고 실행하여 Spring, React, Mysql이 작동하는지 확인합니다.
- Nginx를 이용한 포트포워딩을 수행합니다.

## Tasks
- [x] Spring 수동 배포 스크립트 작성
- [x] React 수동 배포 스크립트 작성
- [x] MySQL 설치
- [x] JDK 설치
- [x] Node.js, npm 설치
